#!/bin/bash
output_file_hc="/root/Desktop/host/PS1/Problem_3/hardcode_result.txt"
>"$output_file_hc"
echo "Hard-coded conversions from Table 1:" >> "$output_file_hc"
echo "Decimal | Hexadecimal | Binary" >> "$output_file_hc"
echo "--------|-------------|--------" >> "$output_file_hc"
echo "1       | 1           | 0001" >> "$output_file_hc"
echo "2       | 2           | 0010" >> "$output_file_hc"
echo "3       | 3           | 0011" >> "$output_file_hc"
echo "4       | 4           | 0100" >> "$output_file_hc"
echo "5       | 5           | 0101" >> "$output_file_hc"
echo "6       | 6           | 0110" >> "$output_file_hc"
echo "7       | 7           | 0111" >> "$output_file_hc"
echo "8       | 8           | 1000" >> "$output_file_hc"
echo "9       | 9           | 1001" >> "$output_file_hc"
echo "10      | A           | 1010" >> "$output_file_hc"
echo "11      | B           | 1011" >> "$output_file_hc"
echo "12      | C           | 1100" >> "$output_file_hc"
echo "13      | D           | 1101" >> "$output_file_hc"
echo "14      | E           | 1110" >> "$output_file_hc"
echo "15      | F           | 1111" >> "$output_file_hc"
echo "16      | 10          | 00010000" >> "$output_file_hc"
echo "26      | 1A          | 00011010" >> "$output_file_hc"
echo "31      | 1F          | 00011111" >> "$output_file_hc"
echo "32      | 20          | 00100000" >> "$output_file_hc"
echo "" >> "$output_file_hc"
echo "Hard-coded decimal to hexadecimal conversion (Table 2):" >> "$output_file_hc"
decimal=125064
hexadecimal="1E888"
binary="111110100010001000"
echo "Decimal: $decimal" >> "$output_file_hc"
echo "Hexadecimal: $hexadecimal" >> "$output_file_hc"
echo "Binary (division by 2): $binary" >> "$output_file_hc"